version: "2"
services:
  node:
    image: "node:9"
    container_name: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
      - ~/.aws:/home/node/.aws
    expose:
      - "8081"
    command: "npm start"